home:
  path: /
  title: Home
  description: Welcome to our tutoring platform

tuition:
  path: /tuition-fee
  title: Tuition Fees
  description: Learn about our tutoring rates and payment options

become-tutor:
  path: /become-tutor
  title: Become a Tutor
  description: Join our tutoring team and start teaching

request-tutor:
  path: /request-tutor
  title: Request a Tutor
  description: Find the perfect tutor for your needs

faq-tutors:
  path: /faq-tutors
  title: FAQ for Tutors
  description: Frequently asked questions for tutors

faq-parents:
  path: /faq-parents
  title: FAQ for Parents
  description: Frequently asked questions for parents and students

about:
  path: /about-us
  title: About Us
  description: Learn more about our tutoring service and mission

contact:
  path: /contact-us
  title: Contact Us
  description: Get in touch with our team

privacy:
  path: /privacy
  title: Privacy Policy
  description: Our privacy policy and data protection practices

terms:
  path: /terms
  title: Terms of Service
  description: Terms and conditions for using our service

chinese-tuition:
  path: /上门补习的学费都是先进家教的口袋吗
  title: 上门补习的学费说明
  description: 了解我们的上门补习收费标准和付款方式