/:
  layout: home
  blocks:
    hero:
      title: Welcome to Our Tutoring Platform
      subtitle: Find your perfect tutor today
      buttons:
        - text: Request a Tutor
          url: /request-tutor
        - text: Become a Tutor
          url: /become-tutor
          
    features:
      title: Why Choose Us
      items:
        - title: Qualified Tutors
          text: All our tutors are carefully screened
        - title: Flexible Schedule
          text: Learn at your own pace and time
        - title: Affordable Rates
          text: Competitive pricing for quality education

/tuition-fee:
  layout: default
  title: Our Tuition Fees

/become-tutor:
  layout: default
  title: Become a Tutor

/request-tutor:
  layout: default
  title: Request a Tutor

/faq-tutors:
  layout: default
  title: FAQ for Tutors

/faq-parents:
  layout: default
  title: FAQ for Parents

/about-us:
  layout: default
  title: About Us

/privacy:
  layout: default
  title: Privacy Policy

/terms:
  layout: default
  title: Terms of Service

/contact-us:
  layout: default
  title: Contact Us

/上门补习的学费都是先进家教的口袋吗:
  layout: default
  title: 上门补习的学费说明