/:  # Home page configuration
  layout: home
  meta:
    title: Your Tutoring Platform
    description: Find the perfect tutor or become one with our leading tutoring service
  blocks:
    - type: hero
      title: Welcome to Our Tutoring Platform
      description: Connect with qualified tutors or start your tutoring journey today
      image: hero-image.jpg
      cta:
        text: Get Started
        link: /request-tutor
    
    - type: features
      items:
        - title: Find a Tutor
          description: Browse our network of qualified tutors
          link: /request-tutor
        - title: Become a Tutor
          description: Join our teaching community
          link: /become-tutor
        - title: Competitive Rates
          description: Check our tuition fees
          link: /tuition-fee
    
    - type: testimonials
      title: What Our Students Say
      items:
        - author: John Doe
          text: "Found my perfect math tutor here!"
        - author: Jane Smith
          text: "Excellent learning experience!"

    - type: cta-section
      title: Ready to Start?
      description: Choose your path to begin
      buttons:
        - text: Request a Tutor
          link: /request-tutor
          primary: true
        - text: Become a Tutor
          link: /become-tutor
          primary: false

tuition:
  path: /tuition-fee
  title: Tuition Fees
  description: Learn about our tutoring rates and payment options

become-tutor:
  path: /become-tutor
  title: Become a Tutor
  description: Join our tutoring team and start teaching

request-tutor:
  path: /request-tutor
  title: Request a Tutor
  description: Find the perfect tutor for your needs

faq-tutors:
  path: /faq-tutors
  title: FAQ for Tutors
  description: Frequently asked questions for tutors

faq-parents:
  path: /faq-parents
  title: FAQ for Parents
  description: Frequently asked questions for parents and students

about:
  path: /about-us
  title: About Us
  description: Learn more about our tutoring service and mission

contact:
  path: /contact-us
  title: Contact Us
  description: Get in touch with our team

privacy:
  path: /privacy
  title: Privacy Policy
  description: Our privacy policy and data protection practices

terms:
  path: /terms
  title: Terms of Service
  description: Terms and conditions for using our service

chinese-tuition:
  path: /上门补习的学费都是先进家教的口袋吗
  title: 上门补习的学费说明
  description: 了解我们的上门补习收费标准和付款方式